service: flask-app

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  memorySize: 128

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  exclude:
    - .git/**
    - .vscode/**
    - node_modules/**
    - tests/**
    - docs/**
    - .serverless/**
functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any

custom:
  wsgi:
    app: app.app  	
    packRequirements: false